"""add tenant code

Revision ID: 665728f44593
Revises: d8b8edfdbfa6
Create Date: 2026-04-25 19:12:14.328247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '665728f44593'
down_revision: Union[str, None] = 'd8b8edfdbfa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('code', sa.String(length=7), nullable=True))
    op.create_index(op.f('ix_tenants_code'), 'tenants', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_code'), table_name='tenants')
    op.drop_column('tenants', 'code')
    # ### end Alembic commands ###
