"""Add goal thresholds to Tenant

Revision ID: f37b1e7d16bc
Revises: 665728f44593
Create Date: 2026-04-25 21:03:04.725838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f37b1e7d16bc'
down_revision: Union[str, None] = '665728f44593'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('base_score_for_goal', sa.Float(), nullable=True))
    op.add_column('tenants', sa.Column('step_for_goal', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'step_for_goal')
    op.drop_column('tenants', 'base_score_for_goal')
    # ### end Alembic commands ###
